/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import alertas.ErrorAlert;
import interaccion_BD.opciones_de_gestionar_usuarios;
import interaccion_BD.opciones_tabla_general;
import java.awt.Component;
import java.awt.MouseInfo;
import java.awt.Point;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import paneles.CambiaPanel;
import paneles.pnlHome;
import paneles.pnl_add;

import paneles.pnl_datos;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author 4l3
 */
public class Principal extends javax.swing.JFrame {

    int x, y;
    private int PosicionMouse;
    public static String usuario="";
    
    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        label_user.setText(usuario);
        panel_botones.setAlignmentX(Component.LEFT_ALIGNMENT);
        scroll_principal.getVerticalScrollBar().setUnitIncrement(16);
        RSUtilities.setIconoVentana(this, "/imagenes/logo_1.png");
        new CambiaPanel(pnlPrincipal,new pnlHome());
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_buscar = new app.bolivia.swing.JCTextField();
        pnlCentro = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_botones = new javax.swing.JPanel();
        btn_permisos = new rojeru_san.RSButtonRiple();
        btn_add = new rojeru_san.RSButtonRiple();
        btn_inicio = new rojeru_san.RSButtonRiple();
        label_salir = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        btn_add1 = new rojeru_san.RSButtonRiple();
        scroll_principal = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Control de Expedientes");

        txt_buscar.setBackground(new java.awt.Color(38, 86, 186));
        txt_buscar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_buscar.setForeground(new java.awt.Color(255, 255, 255));
        txt_buscar.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_buscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_buscar.setPhColor(new java.awt.Color(255, 255, 255));
        txt_buscar.setPlaceholder("BUSCAR");
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 866, Short.MAX_VALUE)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(128, 128, 131));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoo.png"))); // NOI18N

        panel_botones.setOpaque(false);

        btn_permisos.setBackground(new java.awt.Color(255, 255, 255));
        btn_permisos.setForeground(new java.awt.Color(38, 86, 186));
        btn_permisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil.png"))); // NOI18N
        btn_permisos.setText("PERMISOS ");
        btn_permisos.setColorHover(new java.awt.Color(173, 187, 194));
        btn_permisos.setColorText(new java.awt.Color(38, 86, 186));
        btn_permisos.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btn_permisos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_permisos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_permisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_permisosActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(255, 255, 255));
        btn_add.setForeground(new java.awt.Color(38, 86, 186));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btn_add.setText("AÑADIR ");
        btn_add.setColorHover(new java.awt.Color(173, 187, 194));
        btn_add.setColorText(new java.awt.Color(38, 86, 186));
        btn_add.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btn_add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_add.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_inicio.setBackground(new java.awt.Color(255, 255, 255));
        btn_inicio.setForeground(new java.awt.Color(38, 86, 186));
        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.png"))); // NOI18N
        btn_inicio.setText("INICIO ");
        btn_inicio.setColorHover(new java.awt.Color(173, 187, 194));
        btn_inicio.setColorText(new java.awt.Color(38, 86, 186));
        btn_inicio.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btn_inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_inicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        label_salir.setBackground(new java.awt.Color(255, 255, 255));
        label_salir.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label_salir.setForeground(new java.awt.Color(128, 128, 131));
        label_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        label_salir.setText("Salir");
        label_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_salir.setOpaque(true);
        label_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_salirMouseExited(evt);
            }
        });

        label_user.setBackground(new java.awt.Color(255, 255, 255));
        label_user.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        label_user.setForeground(new java.awt.Color(128, 128, 131));
        label_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/label-usuario.png"))); // NOI18N
        label_user.setText("jLabel5");
        label_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_user.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        label_user.setOpaque(true);
        label_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_userMouseExited(evt);
            }
        });

        btn_add1.setBackground(new java.awt.Color(255, 255, 255));
        btn_add1.setForeground(new java.awt.Color(38, 86, 186));
        btn_add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lista.png"))); // NOI18N
        btn_add1.setText("DATOS CARGADOS");
        btn_add1.setColorHover(new java.awt.Color(173, 187, 194));
        btn_add1.setColorText(new java.awt.Color(38, 86, 186));
        btn_add1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btn_add1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_add1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_botonesLayout = new javax.swing.GroupLayout(panel_botones);
        panel_botones.setLayout(panel_botonesLayout);
        panel_botonesLayout.setHorizontalGroup(
            panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_botonesLayout.createSequentialGroup()
                .addComponent(label_salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_permisos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panel_botonesLayout.setVerticalGroup(
            panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_botonesLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_permisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_salir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(panel_botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        scroll_principal.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        scroll_principal.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCentroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scroll_principal)))
                .addContainerGap())
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(scroll_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.4;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        pnl_add.editable=true;
        String sql_permiso="SELECT * FROM permisos WHERE usuario='"+principal.Principal.label_user.getText()+"' and add_contratos='1'";
        String mj1="Usted no cuenta con los permisos requeridos para entrar entrar a esta sección.";
        String mj2="Si considera que estamos en un error contacte con el administrador del ";
        String mj3="sistema para que le otorgue los permisos pertinentes";
        if(opciones_de_gestionar_usuarios.existe(sql_permiso)){
                    try {
                        //opciones_tabla_general.nombre_tabla="usuarios";
                        new CambiaPanel(pnlPrincipal, new pnl_add());
                    } catch (SQLException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
        }else{
            ErrorAlert.lanza_error_variable_sin_ex(mj1, mj2, mj3);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_permisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_permisosActionPerformed
        // TODO add your handling code here:
        String sql_permiso="SELECT * FROM permisos WHERE usuario='"+principal.Principal.label_user.getText()+"' and panel_usuarios='1'";
        String mj1="Usted no cuenta con los permisos requeridos para ejecutar esta acción.";
        String mj2="Si considera que estamos en un error contacte con el administrador del ";
        String mj3="sistema para que le otorgue los permisos pertinentes";
        if(opciones_de_gestionar_usuarios.existe(sql_permiso)){
        opciones_tabla_general.nombre_tabla="usuarios";
       new CambiaPanel(pnlPrincipal, new configuracion.pnl_Gestionar_usuarios());
        }else{
            ErrorAlert.lanza_error_variable_sin_ex(mj1, mj2, mj3);
        }
    }//GEN-LAST:event_btn_permisosActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        // TODO add your handling code here:
        opciones_tabla_general.nombre_tabla="gestion_produccion";
        new CambiaPanel(pnlPrincipal,new pnlHome());
        txt_buscar.setVisible(true);
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        // TODO add your handling code here:
        if (opciones_tabla_general.nombre_tabla.equals("usuarios")) {
            opciones_de_gestionar_usuarios.setListar(txt_buscar.getText());
        } else {
            DefaultTableModel modelo = (DefaultTableModel) pnlHome.tabla_general.getModel();
            while (modelo.getRowCount() > 0) {
                modelo.removeRow(0);
            }
            if (pnlHome.produccion.isSelected()) {
                    opciones_tabla_general.setListar(Principal.txt_buscar.getText(), "gestion_produccion");
            }
            if (pnlHome.base.isSelected()) {
                    opciones_tabla_general.setListar(Principal.txt_buscar.getText(), "sistema_base");
            }
            if (pnlHome.aplicaciones.isSelected()) {
                    opciones_tabla_general.setListar(Principal.txt_buscar.getText(), "gestion_aplicaciones");
            }
            if (pnlHome.comunicaciones.isSelected()) {
                    opciones_tabla_general.setListar(Principal.txt_buscar.getText(), "sistema_comunicaciones");
            }
            
        }

    }//GEN-LAST:event_txt_buscarKeyReleased

    private void label_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_userMouseEntered
        // TODO add your handling code here:
        this.label_user.setBackground(new java.awt.Color(173,187,194));
    }//GEN-LAST:event_label_userMouseEntered

    private void label_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_salirMouseEntered
        // TODO add your handling code here:
        label_salir.setBackground(new java.awt.Color(173,187,194));
    }//GEN-LAST:event_label_salirMouseEntered

    private void label_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_salirMouseExited
        // TODO add your handling code here:
        label_salir.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_label_salirMouseExited

    private void label_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_userMouseExited
        // TODO add your handling code here:
        label_user.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_label_userMouseExited

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        // TODO add your handling code here:
        String sql_permiso="SELECT * FROM permisos WHERE usuario='"+principal.Principal.label_user.getText()+"' and edit_list='1'";
        String mj1="Usted no cuenta con los permisos requeridos para entrar entrar a esta sección.";
        String mj2="Si considera que estamos en un error contacte con el administrador del ";
        String mj3="sistema para que le otorgue los permisos pertinentes";
        if(opciones_de_gestionar_usuarios.existe(sql_permiso)){
        //opciones_tabla_general.nombre_tabla="usuarios";
       new CambiaPanel(pnlPrincipal, new pnl_datos());
        }else{
            ErrorAlert.lanza_error_variable_sin_ex(mj1, mj2, mj3);
        }
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void cierra_sesion(){
        opciones_tabla_general.nombre_tabla="gestion_produccion";
        this.dispose();
    }
    
    private void label_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_salirMouseClicked
        // TODO add your handling code here:
        cierra_sesion();
        new login.login().setVisible(true);
    }//GEN-LAST:event_label_salirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btn_add;
    private rojeru_san.RSButtonRiple btn_add1;
    private rojeru_san.RSButtonRiple btn_inicio;
    private rojeru_san.RSButtonRiple btn_permisos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel label_salir;
    public static javax.swing.JLabel label_user;
    private javax.swing.JPanel panel_botones;
    private javax.swing.JPanel pnlCentro;
    public static javax.swing.JPanel pnlPrincipal;
    public static javax.swing.JScrollPane scroll_principal;
    public static app.bolivia.swing.JCTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
