/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alertas;

import interaccion_BD.opciones_de_gestionar_usuarios;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import necesario.RSAWTUtilities;
import paneles.pnl_datos;
import rojeru_san.complementos.RSMoveObject;
import rojeru_san.complementos.RSUtilities;
import rojeru_san.rsfield.RSTextMaterial;
import rojerusan.RSTableMetro;

/**
 *
 * @author 4l3
 */
public class combo_autoseleccionado extends javax.swing.JDialog {
public static String nombre;
private int PosicionMouse;
String nombre_tabla = "";

    /**
     * Creates new form ErrorAlert
     */
    public combo_autoseleccionado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        addEventKey();
        initComponents();
        RSAWTUtilities.setOpaque(this, false);
        RSUtilities.setCentrarVentana(this);
         RSMoveObject.setMoverVentana(this);
         contenedor_tabla2.setVisible(false);
         contenedor_tabla3.setVisible(false);
         this.menu.add(pnlMenu);
         tabla2.setRowSelectionAllowed(true);
        tabla2.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tabla3.setRowSelectionAllowed(true);
        tabla3.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }
    
    private void addEventKey() {
        KeyStroke enter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false);
        Action enterAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                btnAceptarActionPerformed(e);
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(enter, "ENTER");
        getRootPane().getActionMap().put("ENTER", enterAction);
        //-------------------------------------------------------------------------------
        KeyStroke escape = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action escapeAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escape, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new rojerusan.RSPopuMenu();
        pnlMenu = new javax.swing.JPanel();
        btnBorrar = new rojeru_san.RSButtonRiple();
        btnEditar = new rojeru_san.RSButtonRiple();
        rSPanelShadow1 = new rojeru_san.rspanel.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btncerrar = new rojeru_san.rsbutton.RSButtonRoundEffect();
        btnAceptar = new rojeru_san.rsbutton.RSButtonRoundEffect();
        jPanel2 = new javax.swing.JPanel();
        panel_valores = new javax.swing.JPanel();
        mas2 = new javax.swing.JLabel();
        valor1 = new rojeru_san.rsfield.RSTextMaterial();
        valor2 = new rojeru_san.rsfield.RSTextMaterial();
        valor3 = new rojeru_san.rsfield.RSTextMaterial();
        mas3 = new javax.swing.JLabel();
        panel_tabla = new javax.swing.JPanel();
        contenedor_tabla2 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tabla2 = new rojerusan.RSTableMetro();
        contenedor_tabla3 = new javax.swing.JPanel();
        scroll1 = new javax.swing.JScrollPane();
        tabla3 = new rojerusan.RSTableMetro();

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        btnBorrar.setBackground(new java.awt.Color(69, 87, 252));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contrato/btnEliminar.png"))); // NOI18N
        btnBorrar.setText("ELIMINAR");
        btnBorrar.setColorHover(new java.awt.Color(87, 103, 253));
        btnBorrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(69, 87, 252));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contrato/btnEditar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setColorHover(new java.awt.Color(87, 103, 253));
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        rSPanelShadow1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 86, 186), 10));

        titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(128, 128, 131));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Complete los campos");

        btncerrar.setBackground(new java.awt.Color(255, 255, 255));
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alertas_img/btnSalirBlack.png"))); // NOI18N
        btncerrar.setAutoscrolls(true);
        btncerrar.setColorHover(new java.awt.Color(255, 255, 255));
        btncerrar.setEfecto(rojeru_san.rsbutton.RSButtonRoundEffect.EFECTO.RIPLE);
        btncerrar.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        btncerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptar.setBorder(null);
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alertas_img/aceptarBlack.png"))); // NOI18N
        btnAceptar.setAutoscrolls(true);
        btnAceptar.setColorHover(new java.awt.Color(255, 255, 255));
        btnAceptar.setEfecto(rojeru_san.rsbutton.RSButtonRoundEffect.EFECTO.RIPLE);
        btnAceptar.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panel_valores.setBackground(new java.awt.Color(255, 255, 255));

        mas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N
        mas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas2MouseClicked(evt);
            }
        });

        valor1.setForeground(new java.awt.Color(0, 0, 0));
        valor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor1.setColorMaterial(new java.awt.Color(99, 70, 250));
        valor1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valor1.setPlaceholder("valor1");
        valor1.setSelectionColor(new java.awt.Color(99, 70, 250));
        valor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valor1KeyReleased(evt);
            }
        });

        valor2.setForeground(new java.awt.Color(0, 0, 0));
        valor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor2.setColorMaterial(new java.awt.Color(99, 70, 250));
        valor2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valor2.setPlaceholder("valor2");
        valor2.setSelectionColor(new java.awt.Color(99, 70, 250));
        valor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valor2KeyReleased(evt);
            }
        });

        valor3.setForeground(new java.awt.Color(0, 0, 0));
        valor3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor3.setColorMaterial(new java.awt.Color(99, 70, 250));
        valor3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valor3.setPlaceholder("valor3");
        valor3.setSelectionColor(new java.awt.Color(99, 70, 250));
        valor3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valor3KeyReleased(evt);
            }
        });

        mas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N
        mas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_valoresLayout = new javax.swing.GroupLayout(panel_valores);
        panel_valores.setLayout(panel_valoresLayout);
        panel_valoresLayout.setHorizontalGroup(
            panel_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_valoresLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panel_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(valor1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(valor3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valor2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mas2)
                    .addComponent(mas3))
                .addContainerGap())
        );
        panel_valoresLayout.setVerticalGroup(
            panel_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_valoresLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panel_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mas2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel_valoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mas3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.add(panel_valores);

        panel_tabla.setBackground(new java.awt.Color(255, 255, 255));

        scroll.setBorder(null);

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE USUSARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla2.setToolTipText("");
        tabla2.setAltoHead(30);
        tabla2.setColorBackgoundHead(new java.awt.Color(38, 86, 186));
        tabla2.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tabla2.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tabla2.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tabla2.setColorHoverBackgound(new java.awt.Color(69, 87, 252));
        tabla2.setColorSelBackgound(new java.awt.Color(69, 87, 252));
        tabla2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tabla2.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabla2.setGrosorBordeFilas(0);
        tabla2.setHover(true);
        tabla2.setMultipleSeleccion(false);
        tabla2.setRowHeight(30);
        tabla2.setSelectionBackground(new java.awt.Color(99, 70, 250));
        tabla2.getTableHeader().setReorderingAllowed(false);
        tabla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla2MouseClicked(evt);
            }
        });
        scroll.setViewportView(tabla2);

        javax.swing.GroupLayout contenedor_tabla2Layout = new javax.swing.GroupLayout(contenedor_tabla2);
        contenedor_tabla2.setLayout(contenedor_tabla2Layout);
        contenedor_tabla2Layout.setHorizontalGroup(
            contenedor_tabla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_tabla2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        contenedor_tabla2Layout.setVerticalGroup(
            contenedor_tabla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_tabla2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        scroll1.setBorder(null);

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE USUSARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla3.setToolTipText("");
        tabla3.setAltoHead(30);
        tabla3.setColorBackgoundHead(new java.awt.Color(38, 86, 186));
        tabla3.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tabla3.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tabla3.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tabla3.setColorHoverBackgound(new java.awt.Color(69, 87, 252));
        tabla3.setColorSelBackgound(new java.awt.Color(69, 87, 252));
        tabla3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tabla3.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabla3.setGrosorBordeFilas(0);
        tabla3.setHover(true);
        tabla3.setMultipleSeleccion(false);
        tabla3.setRowHeight(30);
        tabla3.setSelectionBackground(new java.awt.Color(99, 70, 250));
        tabla3.getTableHeader().setReorderingAllowed(false);
        tabla3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla3MouseClicked(evt);
            }
        });
        scroll1.setViewportView(tabla3);

        javax.swing.GroupLayout contenedor_tabla3Layout = new javax.swing.GroupLayout(contenedor_tabla3);
        contenedor_tabla3.setLayout(contenedor_tabla3Layout);
        contenedor_tabla3Layout.setHorizontalGroup(
            contenedor_tabla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_tabla3Layout.createSequentialGroup()
                .addComponent(scroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        contenedor_tabla3Layout.setVerticalGroup(
            contenedor_tabla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_tabla3Layout.createSequentialGroup()
                .addComponent(scroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout panel_tablaLayout = new javax.swing.GroupLayout(panel_tabla);
        panel_tabla.setLayout(panel_tablaLayout);
        panel_tablaLayout.setHorizontalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contenedor_tabla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contenedor_tabla3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_tablaLayout.setVerticalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedor_tabla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contenedor_tabla3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.add(panel_tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 5, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        this.dispose();
        pnl_datos.cerrado_dato_automatico=1;
    }//GEN-LAST:event_btncerrarActionPerformed

    ArrayList temp2 = new ArrayList();
    ArrayList temp3 = new ArrayList();
    public boolean dato_repetido( ArrayList lista, String sql, int num_array){
        boolean repetido=false;
        for(int i=0;i<lista.size();i++){
            if(opciones_de_gestionar_usuarios.existe(sql + lista.get(i).toString() + "'")){
                repetido=true;
                if(num_array==2){
                    temp2.add(lista.get(i).toString());
                }else{
                    temp3.add(lista.get(i).toString());
                }
            }
        }
        System.out.println("temp2 "+temp2);
        System.out.println("temp3 "+temp3);
        return repetido;
    }
    
   public static String placeholder_inicial1="";
   public static String placeholder_inicial2="";
   public static String placeholder_inicial3="";
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if((valor2.getText().isEmpty() && !tabla2.isVisible()) || (valor3.getText().isEmpty() && !tabla3.isVisible())){
            if(valor2.getText().isEmpty() && !tabla2.isVisible()){
                combo_add_unidad.falta_campo(valor2, placeholder_inicial2);
            }
            if(valor3.getText().isEmpty() && !tabla3.isVisible()){
                combo_add_unidad.falta_campo(valor3, placeholder_inicial3);
            }
        }else{
        if(contenedor_tabla2.isVisible()||contenedor_tabla3.isVisible()){
            if(contenedor_tabla2.isVisible()){
                pnl_datos.tablas_visibles=1;
                for(int i=0;i<tabla2.getRowCount();i++){
                    pnl_datos.array2.add(tabla2.getValueAt(i, 0).toString());
                }
                if(!valor2.getText().isEmpty()){
                    pnl_datos.array2.add(valor2.getText());
            }
            }
            if(contenedor_tabla3.isVisible()){
                pnl_datos.tablas_visibles=2;
                for(int i=0;i<tabla3.getRowCount();i++){
                    pnl_datos.array3.add(tabla3.getValueAt(i, 0).toString());
                }
                if(!valor3.getText().isEmpty()){
                    pnl_datos.array3.add(valor3.getText());
            }
            }
            if(contenedor_tabla2.isVisible()&&contenedor_tabla3.isVisible()){
                pnl_datos.tablas_visibles=3;
            }
            // validar si esta repetido alguno de los datos introducidos
            if((opciones_de_gestionar_usuarios.existe("select * from lista_area where resp_area='" + valor1.getText().trim() + "'"))||
                                            (dato_repetido(pnl_datos.array2,"select * from lista_area where resp_area='" ,2))||
                                            (dato_repetido(pnl_datos.array3,"select * from lista_unidad where resp_unidad='",3 )))
                                    {
                                        if(opciones_de_gestionar_usuarios.existe("select * from lista_area where resp_area='" + valor1.getText().trim() + "'")){
                                            ErrorAlert.lanza_error_variable_sin_ex("", "El responsable de area '"+ valor1.getText().trim() +"' ya existe", "");
                                            valor1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
                                            valor1.setColorMaterial(new java.awt.Color(255, 0, 51));
                                            valor1.requestFocus();
                                        }else if(dato_repetido(pnl_datos.array2,"select * from lista_unidad where unidad='" ,2)){
                                            // eliminar duplicados
                                            Set<String> set = new HashSet<>(temp2);
                                            temp2.clear();
                                            temp2.addAll(set);
                                            //---------------------
                                            ErrorAlert.lanza_error_variable_sin_ex("", "La(s) unidad(es) '"+temp2.toString()+"' ya existe(n)", "");
                                            valor2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
                                            valor2.setColorMaterial(new java.awt.Color(255, 0, 51));
                                            for (int i = 0; i < tabla2.getRowCount(); i++) {
                                                for(int l=0;l<temp2.size();l++){
                                                   if (tabla2.getValueAt(i, 0).equals(temp2.get(l))) {                                           
                                                     tabla2.getSelectionModel().addSelectionInterval(i, i);
                                                   } 
                                                }
                                               }
                                            temp2.clear();
                                            valor2.requestFocus();
                                        }else if(dato_repetido(pnl_datos.array3,"select * from lista_unidad where resp_unidad='" ,3)){
                                            System.out.println("dentro resp unidad");
                                             // eliminar duplicados
                                            Set<String> set = new HashSet<>(temp3);
                                            temp3.clear();
                                            temp3.addAll(set);
                                            //---------------------
                                            ErrorAlert.lanza_error_variable_sin_ex("", "El/Los responsable(s) de unidad '"+temp3+"' ya existe", "");
                                            valor3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
                                            valor3.setColorMaterial(new java.awt.Color(255, 0, 51));
                                            for (int i = 0; i < tabla3.getRowCount(); i++) {
                                               for(int l=0;l<temp3.size();l++){
                                                   if (tabla3.getValueAt(i, 0).equals(temp3.get(l))) {                                           
                                                     tabla3.getSelectionModel().addSelectionInterval(i, i);
                                                   } 
                                                }
                                               }
                                            temp3.clear();
                                            valor3.requestFocus();
                                        }
                                    }else{
                dispose();
            }
        }else{
        if(((valor3.isVisible())&&(valor3.getText().isEmpty()))||((valor2.isVisible())&&(valor2.getText().isEmpty()))||((valor1.isVisible())&&(valor1.getText().isEmpty()))){
        if(valor3.isVisible()){
            if(valor3.getText().isEmpty()){
            valor3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
            valor3.setColorMaterial(new java.awt.Color(255, 0, 51));
            valor3.requestFocus();
            valor3.setPlaceholder(placeholder_inicial3+" Inexistente");
        }
        }
        if(valor2.isVisible()){
            if(valor2.getText().isEmpty()){
            valor2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
            valor2.setColorMaterial(new java.awt.Color(255, 0, 51));
            valor2.requestFocus();
            valor2.setPlaceholder(placeholder_inicial2+" Inexistente");
        }
        }
        if(valor1.getText().isEmpty()){
            valor1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
            valor1.setColorMaterial(new java.awt.Color(255, 0, 51));
            valor1.requestFocus();
            valor1.setPlaceholder(placeholder_inicial1+" Inexistente");
        }
        
    }
        else{
            // validar si esta repetido alguno de los datos introducidos
            if((opciones_de_gestionar_usuarios.existe("select * from lista_area where resp_area='" + valor1.getText().trim() + "'"))||
                                            (opciones_de_gestionar_usuarios.existe("select * from lista_unidad where unidad='" + valor2.getText().trim() + "'"))||
                                            (opciones_de_gestionar_usuarios.existe("select * from lista_unidad where resp_unidad='" + valor3.getText().trim() + "'")))
                                    {
                                        if(opciones_de_gestionar_usuarios.existe("select * from lista_area where resp_area='" + valor1.getText().trim() + "'")){
                                            ErrorAlert.lanza_error_variable_sin_ex("", "El responsable de area '"+valor1.getText().trim()+"' ya existe", "");
                                            valor1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
                                            valor1.setColorMaterial(new java.awt.Color(255, 0, 51));
                                            valor1.requestFocus();
                                        }else if(opciones_de_gestionar_usuarios.existe("select * from lista_unidad where unidad='" + valor2.getText().trim() + "'")){
                                            ErrorAlert.lanza_error_variable_sin_ex("", "La unidad '"+valor2.getText().trim()+"' ya existe", "");
                                            valor2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
                                            valor2.setColorMaterial(new java.awt.Color(255, 0, 51));
                                            valor2.requestFocus();
                                        }else if(opciones_de_gestionar_usuarios.existe("select * from lista_unidad where resp_unidad='" + valor3.getText().trim() + "'")){
                                            ErrorAlert.lanza_error_variable_sin_ex("", "El responsable de unidad '"+valor3.getText().trim()+"' ya existe", "");
                                            valor3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
                                            valor3.setColorMaterial(new java.awt.Color(255, 0, 51));
                                            valor3.requestFocus();
                                        }
                                    }else{
                dispose();
            }
        }
        }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void valor1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor1KeyReleased
        // TODO add your handling code here:
        if(valor1.getText().length()>0){
            valor1.setPlaceholder(placeholder_inicial1);
            valor1.setBorder(null);
            valor1.setColorMaterial(new java.awt.Color(99,70,250));
        }
    }//GEN-LAST:event_valor1KeyReleased

    private void valor2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor2KeyReleased
        // TODO add your handling code here:
        if(valor2.getText().length()>0){
            valor2.setPlaceholder(placeholder_inicial2);
            valor2.setBorder(null);
            valor2.setColorMaterial(new java.awt.Color(99,70,250));
        }
    }//GEN-LAST:event_valor2KeyReleased

    private void valor3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor3KeyReleased
        // TODO add your handling code here:
        if(valor3.getText().length()>0){
            valor3.setPlaceholder(placeholder_inicial3);
            valor3.setBorder(null);
            valor3.setColorMaterial(new java.awt.Color(99,70,250));
        }
    }//GEN-LAST:event_valor3KeyReleased

    private void mas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas2MouseClicked
        // TODO add your handling code here:
        boton_mas(valor2,placeholder_inicial2,tabla2,contenedor_tabla2);
    }//GEN-LAST:event_mas2MouseClicked

    private void boton_mas(RSTextMaterial campo, String placeholder, RSTableMetro tabla, JPanel contenedor_tabla){
        if(campo.getText().isEmpty()){
            campo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
            campo.setColorMaterial(new java.awt.Color(255, 0, 51));
            campo.requestFocus();
            campo.setPlaceholder(placeholder+" Inexistente");
        }else{
        JTableHeader head = tabla.getTableHeader();
        TableColumnModel tcm = head.getColumnModel();
        TableColumn tabCM = tcm.getColumn(0);
        tabCM.setHeaderValue(campo.getPlaceholder());
        tabla.repaint();
        DefaultTableModel modelo=(DefaultTableModel) tabla.getModel(); 
        Object [] fila=new Object[1];
        fila[0]=campo.getText(); 
        modelo.addRow(fila); 
        tabla.setModel(modelo); 
        campo.setText("");
        contenedor_tabla.setVisible(true);
        this.preferredSize();
        this.pack();
        }
    }
    
    private void mas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas3MouseClicked
        // TODO add your handling code here:
        boton_mas(valor3,placeholder_inicial3,tabla3,contenedor_tabla3);
    }//GEN-LAST:event_mas3MouseClicked

    private void tabla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla2MouseClicked
        // TODO add your handling code here:
        int row = tabla2.rowAtPoint(evt.getPoint());
        if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) == InputEvent.BUTTON3_MASK) {
            tabla2.setRowSelectionInterval(row, row);
            PosicionMouse = evt.getY() / 16;
            menu.show(evt.getComponent(), evt.getX(), evt.getY());
        } else {
            tabla2.setRowSelectionInterval(row, row);
        }
        nombre_tabla = "tabla2";
    }//GEN-LAST:event_tabla2MouseClicked

    private void centrar_componente(Component c) {
        Dimension pantalla_size = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frame_size = c.getSize();
        if (frame_size.height > pantalla_size.height) {
            frame_size.height = pantalla_size.height;
        }
        if (frame_size.width > pantalla_size.width) {
            frame_size.width = pantalla_size.width;
        }
        c.setLocation((pantalla_size.width - frame_size.width) / 2, (pantalla_size.height - frame_size.height) / 2);
    }
    
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        this.menu.setVisible(false);
        String valor = "";
        int fila=0;
        if (nombre_tabla.equals("tabla2")) {
             fila = this.tabla2.getSelectedRow();
            valor = this.tabla2.getValueAt(fila, 0).toString().trim();
        }
        if (nombre_tabla.equals("tabla3")) {
            fila = this.tabla3.getSelectedRow();
            valor = this.tabla3.getValueAt(fila, 0).toString().trim();
        }
        alertas.WarningAlert w=new alertas.WarningAlert(new JFrame(), true);
//        alertas.WarningAlert w = new alertas.WarningAlert(new JFrame(), true);
        w.msj1.setText("");
        w.msj2.setText("Se eliminara el dato de nombre (" + valor + ")");
        w.msj3.setText("");;
        w.setVisible(true);
        if (w.hecho) {
            if (nombre_tabla.equals("tabla2")) {
                DefaultTableModel modelo=(DefaultTableModel) tabla2.getModel();
                modelo.removeRow(fila);
                if(tabla2.getRowCount()==0){
                    contenedor_tabla2.setVisible(false);
                    this.pack();
                }
            } else if (nombre_tabla.equals("tabla3")) {
                DefaultTableModel modelo=(DefaultTableModel) tabla3.getModel();
                modelo.removeRow(fila);
                if(tabla3.getRowCount()==0){
                    contenedor_tabla3.setVisible(false);
                    this.pack();
                }
            }
             SuccessAlert s = new SuccessAlert(new JFrame(), true);
                    s.msj1.setText("Dato eliminado con éxito");
                    s.msj2.setText("");
                    s.msj3.setText("");
                    centrar_componente(s);
                    s.setVisible(true);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.menu.setVisible(false);
        if (nombre_tabla.equals("tabla2")) {
            int fila = this.tabla2.getSelectedRow();
            valor2.setText(this.tabla2.getValueAt(fila, 0).toString().trim());
            DefaultTableModel modelo=(DefaultTableModel) tabla2.getModel();
                modelo.removeRow(fila);
                if(tabla2.getRowCount()==0){
                    contenedor_tabla2.setVisible(false);
                    this.pack();
                }
                valor2.requestFocus();
        }
        if (nombre_tabla.equals("tabla3")) {
            int fila = this.tabla3.getSelectedRow();
            valor3.setText(this.tabla3.getValueAt(fila, 0).toString().trim());
            DefaultTableModel modelo=(DefaultTableModel) tabla3.getModel();
                modelo.removeRow(fila);
                if(tabla3.getRowCount()==0){
                    contenedor_tabla3.setVisible(false);
                    this.pack();
                }
                valor3.requestFocus();
        }
        this.menu.setVisible(false);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void tabla3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla3MouseClicked
        // TODO add your handling code here:
        int row = tabla3.rowAtPoint(evt.getPoint());
        if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) == InputEvent.BUTTON3_MASK) {
            tabla3.setRowSelectionInterval(row, row);
            PosicionMouse = evt.getY() / 16;
            menu.show(evt.getComponent(), evt.getX(), evt.getY());
        } else {
            tabla3.setRowSelectionInterval(row, row);
        }
        nombre_tabla = "tabla3";
    }//GEN-LAST:event_tabla3MouseClicked

    public static RSTextMaterial getValor1() {
        return valor1;
    }

    public static void setValor1(RSTextMaterial valor1) {
        combo_autoseleccionado.valor1 = valor1;
    }

    public static RSTextMaterial getValor2() {
        return valor2;
    }

    public static void setValor2(RSTextMaterial valor2) {
        combo_autoseleccionado.valor2 = valor2;
    }

    public static RSTextMaterial getValor3() {
        return valor3;
    }

    public static void setValor3(RSTextMaterial valor3) {
        combo_autoseleccionado.valor3 = valor3;
    }

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(combo_autoseleccionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(combo_autoseleccionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(combo_autoseleccionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(combo_autoseleccionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                combo_autoseleccionado dialog = new combo_autoseleccionado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    rojeru_san.rsbutton.RSButtonRoundEffect btnAceptar;
    rojeru_san.RSButtonRiple btnBorrar;
    rojeru_san.RSButtonRiple btnEditar;
    rojeru_san.rsbutton.RSButtonRoundEffect btncerrar;
    javax.swing.JPanel contenedor_tabla2;
    javax.swing.JPanel contenedor_tabla3;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JLabel mas2;
    javax.swing.JLabel mas3;
    rojerusan.RSPopuMenu menu;
    javax.swing.JPanel panel_tabla;
    javax.swing.JPanel panel_valores;
    javax.swing.JPanel pnlMenu;
    rojeru_san.rspanel.RSPanelShadow rSPanelShadow1;
    javax.swing.JScrollPane scroll;
    javax.swing.JScrollPane scroll1;
    public static rojerusan.RSTableMetro tabla2;
    public static rojerusan.RSTableMetro tabla3;
    public static javax.swing.JLabel titulo;
    public static rojeru_san.rsfield.RSTextMaterial valor1;
    public static rojeru_san.rsfield.RSTextMaterial valor2;
    public static rojeru_san.rsfield.RSTextMaterial valor3;
    // End of variables declaration//GEN-END:variables
}
